name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            php: [7.3, 7.4]
            dependency-version: [prefer-lowest, prefer-stable]

        fail-fast: true

    name: PHP${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
        -   name: Checkout code
            uses: actions/checkout@v2

        -   name: Cache dependencies
            uses: actions/checkout@v2
            with:
                path: ~/.composer/cache/files
                key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

        -   name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: ${{ matrix.php }}
                coverage: none

        -   name: Install dependencies
            run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

        -   name: Execute tests
            run: vendor/bin/pest
